### ISSUE TITLE
Application not starting after integrating rinruby in Rails 4.2.6 application

### ISSUE THREAD

**Issue by sebastianzillessen** [clbustos/rinruby#20]
Hi,

I included the gem in my Gemfile of a Rails 4.2.6 application.
After running `bundle install` i tried to execute some code in my `rails console` but unfortunately it is not starting anymore (it starts, but apparently some R script is blocking or delaying the execution, see the screenshot of my header bar of my terminal window)

![screenshot 2016-06-01 20 42 59](https://cloud.githubusercontent.com/assets/300879/15723262/91fac24e-2839-11e6-8cc4-f7cd4c4aea31.png)

Any ideas what could be causing this problem?

Thanks!

My versions are:

- R version 3.3.0 (2016-05-03)
- ruby 2.2.4p230
- Rails 4.2.6
- Working on a Mac
- R installed via homebrew

**Comment by sebastianzillessen** [comment]
As I canceled the execution of `rails c` I saw some errors, maybe this helps:

```
..../gems/rinruby-2.0.3/lib/rinruby.rb:566:in `write': Interrupt
	from ..../gems/rinruby-2.0.3/lib/rinruby.rb:566:in `puts'
	from ..../gems/rinruby-2.0.3/lib/rinruby.rb:566:in `r_rinruby_pull'
	from ..../gems/rinruby-2.0.3/lib/rinruby.rb:181:in `initialise'
	from ..../gems/rinruby-2.0.3/lib/rinruby.rb:789:in `new'
	from ..../gems/rinruby-2.0.3/lib/rinruby.rb:789:in `<top (required)>'
	from ..../gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
	from ..../gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from ..../gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
	from ..../gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
	from ..../gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
	from ..../gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
	from ..../gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
	from ..../config/application.rb:7:in `<top (required)>'
	from ..../gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:141:in `require'
	from ..../gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from ..../gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:67:in `console'
	from ..../gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from ..../gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'

```

**Comment by sebastianzillessen** [comment]
As it seems that this repository is dead: https://github.com/sebastianzillessen/rinruby
