### ISSUE TITLE
Error for popen missing interactive slave

### ISSUE THREAD

**Issue by ghost** [clbustos/rinruby#4]
Hi, I'm getting this error when I try to do a completely different command (rails generate active_admin:install).

Any idea why rinruby is trying to automatically start up R? 

Thanks, Joel

```
 ./lib/ruby/gems/1.9.1/gems/rinruby-2.0.2/lib/rinruby.rb:164:in `popen': 
  No such file or directory - R --interactive --slave (Errno::ENOENT)
from /opt/ruby/ruby-1.9.2-p290/lib/ruby/gems/1.9.1/gems/rinruby-2.0.2/lib/rinruby.rb:164:in `initialize'
from /opt/ruby/ruby-1.9.2-p290/lib/ruby/gems/1.9.1/gems/rinruby-2.0.2/lib/rinruby.rb:789:in `new'
from /opt/ruby/ruby-1.9.2-p290/lib/ruby/gems/1.9.1/gems/rinruby-2.0.2/lib/rinruby.rb:789:in `<top (required)>'
from /opt/ruby/ruby-1.9.2-p290/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `require'
   ...
```

**Comment by pilarcormo** [comment]
@kumarsaurabh20 I have the same problem. Did you manage to fix it? Thank you!

**Comment by kumarsaurabh20** [comment]
@pilarcormo  I think I was getting this error because rails was not detecting R in the production environment. I did solve this problem by adding the following line in the .htaccess file in the public folder of my production server.

SetEnv PATH Path/to/your/server/R/bin
